### RNAseq Analysis
This analysis uses the edgeR package to visualize the counts of data from [Schurch et al, 2016](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4878611/).

```{r setup, echo=TRUE}
library("edgeR")
files <- c(
"ERR458493.fastq.gz.quant.counts",
"ERR458494.fastq.gz.quant.counts",
"ERR458500.fastq.gz.quant.counts",
"ERR458501.fastq.gz.quant.counts")
labels=c("A", "B", "C", "D")
data <- readDGE(files)
```

```{r data, echo=TRUE}
print(data)
```

###

```{r dge, echo=TRUE}
group <- c(rep("mut", 2), rep("wt", 2))
dge = DGEList(counts=data, group=group)
dge <- estimateCommonDisp(dge)
dge <- estimateTagwiseDisp(dge)
```

# Make an MA-plot

```{r MA plot}
et <- exactTest(dge, pair=c("wt", "mut"))
etp <- topTags(et, n=100000)
etp$table$logFC = -etp$table$logFC
#pdf("yeast-edgeR-MA-plot.pdf")
plot(
etp$table$logCPM,
etp$table$logFC,
xlim=c(-3, 20), ylim=c(-12, 12), pch=20, cex=.3,
col = ifelse( etp$table$FDR < .2, "red", "black" ) )
#dev.off()
```

# plot MDS

``` {r MDS plot, include=FALSE}
pdf("yeast-edgeR-MDS.pdf")
plotMDS(dge, labels=labels)
dev.off()
```

```{r csv, include=FALSE}
# output CSV for 0-6 hr
write.csv(etp$table, "yeast-edgeR.csv")
